spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  datasource:
    driverClassName: mongodb.jdbc.MongoDriver
  http:
    multipart:
      max-file-size: 170MB
      max-request-size: 170MB
      
server:
  port: 8080

    